// app/superslide/page.tsx
import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Superslide | Creeperkatze",
};

export default function Page() {
  return (
    <div>
      <Image
        src="/images/superslide/GameTitle1024.png"
        alt="SUPERSLIDE"
        width="800"
        height="0"
        className="mx-auto"
      />
      <p>
        Mirror version of the{" "}
        <a href="https://creeperkatze.itch.io/superslide">Itch.io game</a>{" "}
        coming here soon...
      </p>

      <a href="/">
        <h3 className="pt-5">Home</h3>
      </a>
    </div>
  );
}

// pages/projects/superslide.vue
<template>
    <img src="~/assets/images/superslide/GameTitle1024.png" width="800" class="center mb-5">
    <iframe class="center rounded-lg" frameborder="0"
        src="https://itch.io/embed/2402263?bg_color=ffffff&amp;fg_color=222222&amp;link_color=327345&amp;border_color=bebebe"
        width="552" height="167"><a href="https://creeperkatze.itch.io/superslide">Superslide by
            Creeperkatze</a></iframe>
    <p class="center mt-5">Mirror version coming here soon...</p>
</template>

<script setup lang="ts">
useHead({
    title: 'Superslide | Creeperkatze',
})
useSeoMeta({
    ogImage: "/seo/GameIcon.png",
    twitterImage: "/seo/GameIcon.png",
})
</script>
